### ISSUE TITLE
How to install it when Docker is used?

### ISSUE THREAD

**Issue by JaneX8** [jeremywillans/lovelace-roomba-vacuum-card#1]
Hi,
I've just started to use Home Assistant and setup my Roomba using the instructions here: https://www.home-assistant.io/integrations/roomba/. However I don't manager to get any info of my Roomba (battery status, current activity etc). I can simply start my Roomba with one button from a card now but thats it.

In developer tools however I did see this:

```
status: Charging
battery_level: 100
battery_icon: 'mdi:battery-charging-100'
software_version: lewis+3.2.9+lewis-release-rt419+12
bin_present: true
bin_full: false
position: '(0, 0, 0)'
friendly_name: Roomba
supported_features: 991

```

I would like to use your or another card for that but I run Home Assistant from a Docker container and cannot easily access the `www` folder, also don't really want. I can access my configuration folder, as it is shared with the host. Also your HACS url in README is broken. Whats the best way forward?

**Comment by jeremywillans** [comment]
Hi @ElleshaHackett,

This card is not designed to work with the built in roomba integration, instead using the seperate rest980 addon and sensor config from this GH Repo

https://github.com/jeremywillans/ha-rest980-roomba

I also run HA in docker, and the www directory HA uses is actually within your configuration directory. 

However I highly recommend you install HACS (link has been fixed) as there are lots of great community driven components and plugins that extend the built in HA options 👍

**Comment by jeremywillans** [comment]
Please reach out if you have any further questions! Best point of contact is this forum thread
https://community.home-assistant.io/t/irobot-roomba-i7-configuration-using-rest980/
