### ISSUE TITLE
Robot_States object

### ISSUE THREAD

**Issue by LukaszZdunek** [jeremywillans/lovelace-roomba-vacuum-card#12]
Hi, 
Please tell me where i'm must past translate "Robot_States"
`
robot_states:
  ready: Gotowy
  stuck: Zablokowany
`
I'm try paste this code in Lovelance Card and vacuum.yaml but language has not change...

Please help me.

Thanks,

**Comment by jeremywillans** [comment]
Hi @LukaszZdunek,

The State names need to be passed over from the integration, the state names in the lovelace card are used for state mapping for determing which buttons to show.

You will need to update the values [here](https://github.com/jeremywillans/ha-rest980-roomba/blob/master/vacuum.yaml#L44) and [here](https://github.com/jeremywillans/ha-rest980-roomba/blob/master/vacuum.yaml#L92)

**Comment by jeremywillans** [comment]
bump
