### ISSUE TITLE
How to use with a second Roomba?

### ISSUE THREAD

**Issue by tagno25** [jeremywillans/lovelace-roomba-vacuum-card#3]
This card seems to mostly work with multiple Roombas, but the buttons seem to only work with the first one.  It seems that the rest action for the buttons is hard coded to use "vacuum_action".

Is there a way to have multiple roomabs work with one rest command, or is there some other way to have the buttons work with multiple roombas?

**Comment by jeremywillans** [comment]
Good Pickup! Fixed in 0.7 Release 👍
