### ISSUE TITLE
Not displaying with 116.1

### ISSUE THREAD

**Issue by tech165** [jeremywillans/lovelace-roomba-vacuum-card#4]
Hi, the card is not displaying anymore with 116.1. 

Look like it's related to lazy loading but not 100% sure.

If you need any other info let me know I will gladly provide them. 

This link info about it :https://developers.home-assistant.io/blog/2020/10/02/lazymoreinfo/

Thanks

**Comment by rpitera** [comment]
Same here, thought it was just me. `<sigh of relief>` Can't see any obvious errors in either HA logs or DevTools in Chrome.

Standing by to provide whatever info I can.  Just to confirm; all the sensors still work it's just the card isn't loading.

**Comment by tech165** [comment]
Hi have created a pull request. It is working on my side with 116. Should also work on pre 116 but not tested.

Great explanation : https://developers.home-assistant.io/blog/2020/09/30/customviewchanges/

Thanks

**Comment by rpitera** [comment]
@tech165 - Renamed both the .js and the js.gz files to test. After a refresh or two, it was displaying again.  So working here with 0.116.1.

`Important note to others! If testing, you must rename BOTH or else it will fall back to using the gzipped cache!`

Thanks for the quick response!

**Comment by jeremywillans** [comment]
Merged #5 - Thanks @tech165
