### ISSUE TITLE
Most fields not populating

### ISSUE THREAD

**Issue by stu1811** [jeremywillans/lovelace-roomba-vacuum-card#7]
I have an s9+ and I installed this card via hacs. Only the name is populated. Do I need to add some different config options? 
I have the following entities available:
vacuum.dustyv2
sensor.dustyv2_battery_level
binary_sensor.dustyv2_bin_full
![image](https://user-images.githubusercontent.com/12236842/115172460-56184580-a093-11eb-80b6-46c63945a04e.png)

**Comment by jeremywillans** [comment]
Please refer my [ha-rest980-roomba](https://github.com/jeremywillans/ha-rest980-roomba) GitHub Repository for detailed instructions for using this card.

This card does not work with the inbuilt vacuum integration in HA
