### ISSUE TITLE
All info without Map

### ISSUE THREAD

**Issue by AlekeiPL** [jeremywillans/lovelace-roomba-vacuum-card#9]
Hello,
I really admire your work! But is there any option for all data to be displayed on the card (just like yours) without creating a map? Because there is an inscription "unavailable" on my card. Thank you for your answer.

**Comment by jeremywillans** [comment]
If you follow the steps on the rest980-roomba repo, the card will properly populate with all the details. You can delete the automations for getting the location data and populating the log file
